# From https://model-checking.github.io/kani/install-github-ci.html
name: Kani CI
on:
  schedule:
    - cron: '59 23 * * *'       # midnight every day.
jobs:
  run-kani:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout your code.'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: 'Run Kani on your code.'
        uses: model-checking/kani-github-action@f838096619a707b0f6b2118cf435eaccfa33e51f # v1.1
        with:
          args: "--package bitcoin-dogecoin --package bitcoin-units"
